language: php

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.6
        - php: 5.6
          env: WITH_CRYPTO=true
        - php: 7.0
        - php: 7.0
          env: WITH_CRYPTO=true
        - php: hhvm
        - php: nightly

before_script:
    - sh -c 'if [ "$WITH_CRYPTO" != "" ]; then pecl install crypto-0.2.2; fi;'
    - composer install --no-interaction
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - vendor/bin/coveralls --no-interaction
    - php ./examples/Encrypt1.php
    - php ./examples/Encrypt2.php
    - php ./examples/Signature1.php
    - php ./examples/Signature2.php
    - php ./examples/Load1.php
    - php ./examples/Load2.php
    - php ./examples/Load3.php
    - php ./examples/Load4.php
