language: php

sudo: true

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
    fast_finish: true
    include:
        - php: 5.6
          env: deps=low
        - php: 5.6
        - php: 7.0
        - php: 7.0
          env: deps=low
        - php: 7.1
        - php: hhvm
        - php: hhvm
          env: deps=low
        - php: nightly

before_script:
    - composer self-update
    - sh -c 'if [ "$WITH_CRYPTO" != "" ]; then pecl install crypto-0.2.2; fi;'
    - mkdir -p build/logs
    - chmod +x tests/ci/install_php_ext.sh
    - if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then ./tests/ci/install_php_ext.sh; fi
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - vendor/bin/coveralls --no-interaction
