language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pecl install crypto-0.1.1; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add ./tests/php.ini; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then composer remove "ext-crypto"; fi;'
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar update --dev --no-interaction

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi;'
